---
stages:
  - name: Build Stage
    inputs:
      - type: git
        branch: master
        service:
          service_id: github_integrated
          parameters:
            repo_name: iot4i-starter-app-backend
            repo_url: https://github.com/ibm-watson-iot/ioti-starter-app-backend
            type: clone
            has_issues: false
    triggers:
      - type: commit
    jobs:
      - name: Build
        type: builder
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build Stage
        job: Build
    triggers:
      - type: stage
    jobs:
      - name: Deploy to dev
        type: deployer
        script: |-
          #!/bin/bash
          #Remove the 'export' and 'sed' lines from the configuration of 
          #the Deploy Stage when you have set APP_ENV in the manifest.yml and created a 
          #corresponding config/config-$env.json file
          export APP_ENV=template
          sed -i  "s/myenv/$APP_ENV/g" manifest.yml
          cf create-service cloudantNoSQLDB Lite iot4i-starter-cloudantNoSQLDB
          cf push "${CF_APP}" --no-start
          cf bind-service "${CF_APP}" iot4i-starter-cloudantNoSQLDB
          cf start "${CF_APP}"
        target:
          organization: ${CF_ORGANIZATION}
          space: ${CF_SPACE}
          url: ${CF_TARGET_URL}
          application: ${CF_APP}
