---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
    service: ${POLICY_HOLDER_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
      #!/bin/bash
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      npm install
      node_modules/bower/bin/bower install
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: ENV
    value: staging
    type: text
  - name: BACKEND_APP_NAME
    value: ${BACKEND_APP_NAME}
    type: text
  - name: TENANT_ID
    value: ${TENANT_ID}
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${STAGING_REGION_ID}
      organization: ${STAGING_ORG_NAME}
      space: ${STAGING_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      #Need to set node version for brunch to work
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      sed -i "s/[<]backendhost[>]:[<]port[>]/${BACKEND_APP_NAME}.mybluemix.net/g" app/config-${ENV}.js
      sed -i "s/[<]tenantid[>]/${TENANT_ID}/g" app/config-${ENV}.js
      sed -i "s/iot4i-starter-app/${CF_APP}/g" manifest.yml
      #brunch after seds
      node_modules/brunch/bin/brunch b --env "${ENV}"
      cd public
      cf push "${CF_APP}" --no-start
      cf start "${CF_APP}"
