---
stages:
  - name: Build Stage
    inputs:
      - type: git
        branch: master
        service: ${POLICY_HOLDER_REPO}
    triggers:
      - type: commit
    jobs:
      - name: Build
        type: builder
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build Stage
        job: Build
    triggers:
      - type: stage
    properties:
      - name: ENV
        value: staging
        type: text
      - name: BACKEND_APP_NAME
        value: ${BACKEND_APP_NAME}
        type: text
    jobs:
      - name: Deploy
        type: deployer
        script: |-
          #!/bin/bash
          env
          sed -i "s/[<]backendhost[>]:[<]port[>]/${BACKEND_APP_NAME}/g" app/config-${ENV}.js  
          cat app/config-${ENV}.js
          sed -i "s/iot4i-starter-app/${CF_APP}/g" manifest.yml
          cat manifest.yml
          cf push "${CF_APP}" --no-start
          cf start "${CF_APP}"
        target:
          region_id: ${STAGING_REGION_ID}
          organization: ${STAGING_ORG_NAME}
          space: ${STAGING_SPACE_NAME}
          application: ${CF_APP_NAME}

